### ISSUE TITLE
[BUG] Change Location multi-word locations

### ISSUE THREAD

**Issue by builderjer** [NeonGeckoCom/skill-user_settings#65]
### Description

multi word locations not working

### Steps to Reproduce

ask to change my location to orchard city colorado
it works if I use single word locations 
change my location to hotchkiss colorado

### Relevant Code

This is the log from doing so
```
2023-03-08 13:45:51.340 - skills - mycroft.skills.intent_service:_normalize_all_utterances:61 - DEBUG - Utterances: [('change my location to orchard city colorado',)]
2023-03-08 13:45:51.881 - skills - mycroft.skills.intent_services.padatious_service:_match_level:87 - DEBUG - Padatious Matching confidence > 0.95
2023-03-08 13:45:53.102 - skills - neon_utils.skills.mycroft_skill:speak:161 - DEBUG - Skill speak! {'utterance': 'Would you also like to change your timezone to orchard city colorado?', 'expect_response': False, 'meta': {'skill': 'UserSettingsSkill'}, 'speaker': None, 'speak_ident': '1678283153.0283659'}
2023-03-08 13:45:53.150 - skills - neon_utils.skills.mycroft_skill:speak:162 - DEBUG - speak
2023-03-08 13:45:53.241 - skills - neon_utils.skills.mycroft_skill:speak:171 - DEBUG - Using legacy isSpeaking signal
2023-03-08 13:46:00.072 - skills - mycroft.skills.intent_service:_normalize_all_utterances:61 - DEBUG - Utterances: [('no',)]
2023-03-08 13:46:00.925 - skills - neon_utils.skills.mycroft_skill:converse:348 - INFO - Got response: no
2023-03-08 13:46:01.187 - skills - neon_utils.skills.mycroft_skill:_wait_response:309 - DEBUG - Returning validated response
2023-03-08 13:46:01.301 - skills - neon_utils.skills.mycroft_skill:speak:161 - DEBUG - Skill speak! {'utterance': 'An error occurred while processing a request in User Settings Skill', 'expect_response': False, 'meta': {'skill': 'UserSettingsSkill'}, 'speaker': None, 'speak_ident': '1678283161.2918248'}
2023-03-08 13:46:01.335 - skills - neon_utils.skills.mycroft_skill:speak:162 - DEBUG - speak
2023-03-08 13:46:01.351 - skills - ovos_workshop.skills.base:_on_event_error:1256 - ERROR - 'city'
Traceback (most recent call last):
  File "/home/ovos/.local/lib/python3.9/site-packages/ovos_utils/messagebus.py", line 352, in wrapper
    handler(message)
  File "/home/ovos/.local/lib/python3.9/site-packages/skill_user_settings/__init__.py", line 332, in handle_change_location_timezone
    'city': resolved_place['address']['city'],
KeyError: 'city'
```

### Other Notes

Running OVOS Version: 0.0.7a10 not neon

**Comment by NeonDaniel** [comment]
It looks like the issue here is I assumed openstreetmap would provide a `city`, but in this case it provides `village`. Good catch and this will probably help some other locations too

```
{'village': 'Orchard City', 'county': 'Delta County', 'state': 'Colorado', 'ISO3166-2-lvl4': 'US-CO', 'postcode': '81418', 'country': 'United States', 'country_code': 'us'}
```
